[package]
org = "choreo"
name = "mediation.add_query_param"
version = "1.0.0"
distribution = "2201.2.3"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
