[package]
org = "choreo"
name = "mediation.xml_to_json"
version = "0.3.1"
distribution = "2201.2.3"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow", "choreo-apim-mediation-response-flow"]

[build-options]
observabilityIncluded = true
