[package]
org = "choreo"
name = "mediation.xml_to_json"
version = "0.3.0"
distribution = "2201.1.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-inflow", "choreo-apim-mediation-outflow"]

[build-options]
observabilityIncluded = true
