[package]
org = "choreo"
name = "mediation.add_header"
version = "0.3.0"
distribution = "2201.1.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-inflow", "choreo-apim-mediation-outflow", "choreo-apim-mediation-faultflow"]

[build-options]
observabilityIncluded = true
