[package]
org = "choreo"
name = "mediation.remove_header"
version = "1.0.0"
distribution = "2201.2.3"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow", "choreo-apim-mediation-response-flow", "choreo-apim-mediation-fault-flow"]

[build-options]
observabilityIncluded = true
