[package]
org = "choreo"
name = "mediation.rewrite_resource_path"
version = "2.0.0"
distribution = "2201.3.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
